$pdf_mode = 5;
$xelatex = 'xelatex -synctex=1 -interaction=nonstopmode -file-line-error %O %S';
$bibtex_use = 2;
$biber = 'biber %O %B';
$out_dir = 'build';
$aux_dir = 'build';
@generated_exts = (@generated_exts, 'bbl', 'bcf', 'run.xml', 'synctex.gz');
